// <auto-generated />
using Bookstore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Api.Data.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20260815180324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Api.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId");

                    b.HasIndex("Name");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Ismail Kadare"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Dritëro Agolli"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "Migjeni"
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Naim Frashëri"
                        });
                });

            modelBuilder.Entity("Bookstore.Api.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Title = "Gjenerali i ushtrisë së vdekur"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            Title = "Kronikë në gur"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            Title = "Pallati i ëndrrave"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 2,
                            Title = "Shkëlqimi dhe rënia e shokut Zylo"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 2,
                            Title = "Komisari Memo"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 3,
                            Title = "Vargjet e lira"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 4,
                            Title = "Bagëti e Bujqësia"
                        });
                });

            modelBuilder.Entity("Bookstore.Api.Entities.Book", b =>
                {
                    b.HasOne("Bookstore.Api.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bookstore.Api.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
